# Generated by Django 2.2.9 on 2020-01-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='url_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('url_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Url_Details')),
            ],
        ),
    ]
