# Generated by Django 2.2.9 on 2020-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='super_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_user_name', models.CharField(max_length=20)),
                ('base_user', models.ManyToManyField(to='app.user_liked')),
            ],
        ),
    ]
