# Generated by Django 2.2.9 on 2020-01-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_super_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='super_user',
            name='super_user_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
