# Generated by Django 2.2.9 on 2020-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200115_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_liked',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_liked',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
