# Generated by Django 2.2.9 on 2020-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200115_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='url_details',
            name='url',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
