
USER_URL='medium.com/'
URL_DATA_COLLECTION='url_data'
URL_META_COLLECTION_NAME='urls_meta'
URL_COLLECTION_NAME='urls'
URL_TF_IDF_COLLECTION='url_tf_idf'
URL_DF_COLLECTION = 'url_df'
WORD_COUNT_LIST = {}
DOCUMENT_ID_LIST=[]