# Generated by Django 2.2.9 on 2020-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UrlDetails',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_user_name', models.CharField(max_length=20)),
                ('user_urls', models.ManyToManyField(to='recommend_app.RecommendedArticle')),
            ],
        ),
        migrations.AddField(
            model_name='recommendedarticle',
            name='liked_urls',
            field=models.ManyToManyField(to='recommend_app.UrlDetails'),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('liked_urls', models.ManyToManyField(to='recommend_app.UrlDetails')),
            ],
        ),
    ]
