# Generated by Django 2.2.9 on 2020-01-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='url_details',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='super_user',
            fields=[
                ('super_user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('base_user', models.ManyToManyField(to='recommend_app.app_user')),
            ],
        ),
        migrations.AddField(
            model_name='app_user',
            name='liked_urls',
            field=models.ManyToManyField(to='recommend_app.url_details'),
        ),
    ]
