# Generated by Django 2.2.9 on 2020-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_details',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url_details',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
