# Generated by Django 2.2.9 on 2020-01-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0002_auto_20200115_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_user',
            name='base_user',
        ),
        migrations.CreateModel(
            name='recommended_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_urls', models.ManyToManyField(to='recommend_app.url_details')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommend_app.app_user')),
            ],
        ),
        migrations.AddField(
            model_name='super_user',
            name='user_urls',
            field=models.ManyToManyField(to='recommend_app.recommended_urls'),
        ),
    ]
