# Generated by Django 2.2.9 on 2020-01-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0003_auto_20200115_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended_urls',
            name='id',
        ),
        migrations.AlterField(
            model_name='recommended_urls',
            name='user',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
