# Generated by Django 2.2.9 on 2020-01-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0004_auto_20200116_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommended_article',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('liked_urls', models.ManyToManyField(to='recommend_app.url_details')),
            ],
        ),
        migrations.AlterField(
            model_name='super_user',
            name='user_urls',
            field=models.ManyToManyField(to='recommend_app.recommended_article'),
        ),
        migrations.DeleteModel(
            name='recommended_urls',
        ),
    ]
