# Generated by Django 2.2.4 on 2020-01-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articleModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('claps', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('articleType', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('articleUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
